name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
    workflow_dispatch:
    

jobs:
  checkPalindrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if text is a palindrome
        run: |
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          text_file="palindrome.txt"

          if [ -f "$text_file" ]; then
            text=$(cat "$text_file")
            echo "::set-output name=text::$text"
          else
            echo "Text file not found."
            exit 1
          fi

      - name: Check palindrome with C++
        if: steps.checkPalindrome.outputs.text != ''
        run: |
          echo "${{ steps.checkPalindrome.outputs.text }}" > input.txt
          g++ -o palindrome_check - <<EOF
          #include <iostream>
          #include <string>
          #include <algorithm>

          using namespace std;

          bool isPalindrome(const string& str) {
            string reversed = str;
            reverse(reversed.begin(), reversed.end());
            return str == reversed;
          }

          int main() {
            string input;
            cin >> input;

            if (isPalindrome(input)) {
              cout << "The text is a palindrome." << endl;
            } else {
              cout << "The text is not a palindrome." << endl;
            }

            return 0;
          }
          EOF

      - name: Run palindrome check
        run: |
          ./palindrome_check < input.txt
