name: Palindrome Check

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  workflow_dispatch:

jobs:
  palindrome_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Compile C++ program
        run: g++ palindrome_check.cpp -o palindrome_check

      - name: Check if file changes form a palindrome
        run: |
          # Check if the changes made in the text file form a palindrome
          file_changes=$(git diff --name-only ${{ github.base_ref }}...${{ github.head_ref }})

          for file in $file_changes; do
            if [[ $file == *.txt ]]; then
              changed_content=$(git diff ${{ github.base_ref }}...${{ github.head_ref }} -- $file | tail -n +5 | awk '{print $1}' | tr -d '+-')
              echo "$changed_content" > temp.txt

              ./palindrome_check temp.txt
            fi
          done
