name: Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
    workflow_dispatch:

jobs:
  checkPalindrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if text is a palindrome
        run: |
          echo "${{ github.event.pull_request.head.repo.full_name }}"
          text_file="palindrome.txt"

          if [ -f "$text_file" ]; then
            text=$(cat "$text_file")
            echo "::set-output name=text::$text"
          else
            echo "Text file not found."
            exit 1
          fi

      - name: Compile and run palindrome_check
        run: |
          g++ -o palindrome_check palindrome_check.cpp
          ./palindrome_check <<< "${{ steps.checkPalindrome.outputs.text }}"
